### ISSUE TITLE
sftp issues

### ISSUE THREAD

**Issue by pwwang** [mkloubert/vscode-remote-workspace#1]
Great extension! But I am facing some issues while using the sftp protocol:
1. Symbolic links are not recognized.
2. We have to put password in the URI? It's showing in the "OPEN EDITORS". "tryKeyboard" seems not working. What about some ssh servers using RSA token as authentication to login?
3. Can we echo something to the server timely to keep the session alive for longer time?
Thanks!

**Comment by pwwang** [comment]
@mkloubert Thanks for the update. I tried the new version on different machines, seems I couldn't connect the server even with `username:password` explicitly in the URI.
For `auth` parameter, I was on Windows, so I used `auth=D:\\auth.txt`. Does that make any sense?

**Comment by mkloubert** [comment]
@pwwang 

You also have to encode that path and you should not use double backslashes: `D:\auth.txt` becomes `D%3A%5Cauth.txt` in your case.

My suggestion is, to store that file into your user directory, something like `C:\Users\pwwang\auth.txt`, so you only need to setup the parameter as `auth=auth.txt`, because relative paths will be mapped to the home directory of the currently running user.

**Comment by mkloubert** [comment]
@pwwang 

BTW.: `tryKeyboard` should work now since version 0.17.0.

**Comment by mkloubert** [comment]
@pwwang 

`tryKeyboard` works for me ... It does not mean that you have to input the credentials. You always have to setup the username and password!

`tryKeyboard` is an "internal" SSH thing, it has nothing to do with the GUI and VS Code ... have a look at [that documentation](https://github.com/mscdex/ssh2) to get more information, what this setting means.

**Comment by pwwang** [comment]
@mkloubert That documentation says it's a keyboard-interactive user authentication if primary authentication fails. I am a little confused. Does that mean I have to put a fake password in the URI? How did it work for you? Could you please give a demo on that? Thank you so much!

**Comment by mkloubert** [comment]
@pwwang 

This setting "simulates" an user interaction and depends on the SSH config. The underlying module is non-interactive.

You always have to setup the real password in the URL or an auth file, no fake one!

If the server does not accept the "standard" login, it sends a request for a "try keyboard" event and the module does a secondary login method, defined with the password, you have defined.

**Comment by pwwang** [comment]
@mkloubert Thanks for the explanation, I understand now.
So is the authentication of this extension relying on ssh2-sftp-client/ssh2? I have read their docs, found there is no method for an ssh server using RSA securID token to login. Does that mean it's also not supported by remote-workspace?

**Comment by mkloubert** [comment]
@pwwang 

That right, I am using `ssh2-sftp-client/ssh2` module for this.

What do you mean with "RSA securID token"? Login with private / public key?

If so: This is supported by the module and that extension. For this, you have to use `key` and/or `phrase` [parameters](https://github.com/mkloubert/vscode-remote-workspace#parameters--4).
