### ISSUE TITLE
Introduce additional library for handling FTPS connections

### ISSUE THREAD

**Issue by hajekj** [mkloubert/vscode-remote-workspace#14]
FTPS connections seem to work quite fine, except with both FTP libraries, I have hit following issue on certain servers: https://github.com/icetee/node-ftp/issues/6

I have recently discovered https://github.com/patrickjuchli/basic-ftp which seems to work fine. Would it be possible to either replace the libraries for FTPS with this one, or ditch the node-ftp library and keep the newer one alongside with this one?

I am not quite sure about this since the plugin could then end up quite heavy with having to carry quite a lot of packages along.

**Comment by mkloubert** [comment]
@hajekj 

I am not sure, but the [README](https://github.com/patrickjuchli/basic-ftp#dependencies) says that at least Node.js 8.0 is required ... VSCode (1.24.0) runs with 7.9.0.
