### ISSUE TITLE
How to interrupt my remote command?

### ISSUE THREAD

**Issue by Davidham3** [mkloubert/vscode-remote-workspace#16]
I used a SFTP mode to load my workspace, I usde F1 to execute remote command, just like "python test.py", and then I can see the results.
But after that, I modified my program, and want to save it, it failed, nothing happened, and the status of that file was still unsaved.
It seems to be stucked, is there any way to shutdown the program or to continue doing something?  Now I can execute the command again or execute other commands like 'echo "test"', they all had results shown on the screen, but I just can't save my file.

**Comment by mkloubert** [comment]
@Davidham3 

**The bug should be fixed now since version 0.26.1**.

The problem was, that command executions uses own connections, which are not cached, but in the last version killed those cached connections, which are used by file operations, what produces some problems.
