### ISSUE TITLE
WebDAV model Chinese text content gibberish

### ISSUE THREAD

**Issue by seekwe** [mkloubert/vscode-remote-workspace#17]
Chinese text content gibberish, file name is no problem.
Other patterns SFTP, no problem.

**Comment by seekwe** [comment]
Ok, thank you

**Comment by seekwe** [comment]
vscode-remote-workspace create the file no problem,
But closed vscode open again or open the vscode-remote-workspace created file is garbled

**Comment by mkloubert** [comment]
@seekwe 

Have you tried an encoding like `utf8`? Maybe the problem is, that used module [isBinaryFile](https://github.com/gjtorikian/isBinaryFile) does detect chinese text files as binary content.

**Comment by seekwe** [comment]
Use encoding=utf8, so the file created by vscode is normal, but the MD file or TXT file created in other places will not work. For the time being, you can only view the file created by vscode. 

It is strange that sftp and the like have no such problem.

 If you don't have a better solution for the time being, let's do it this way. 

Thank you for providing such a convenient plugin.

**Comment by seekwe** [comment]
`encoding=utf8&binEncoding=utf8`

perfect.

Thank you very much!
