### ISSUE TITLE
Open multiple files at same time

### ISSUE THREAD

**Issue by jblong777** [mkloubert/vscode-remote-workspace#31]
Is there a setting to allow to open multiple remote files at once?  When I have one file open and I click on a second file to open, it closes the first and replaces it with the second.  Can it not just open the second file in a new tab?  It works if I open it with the "Open to the Side" command, but I don't want it in a side by side mode I want to be able to switch between them.

**Comment by JeremyBackus** [comment]
It looks like if you open a second file without making any changes to the first file it opens in the same tab.  But if you open a file, make a change, then open another, make a change, open another... etc. they will all be in different tabs.

**Comment by jblong777** [comment]
Yes, you are right.  It will only open another file in a separate tab if the first one has been edited.  So this issue isn't that big of a deal with this workaround, but it would still be nice to just be able to select all of the files I need to work on at once instead of having to "touch" each one before opening the next.

**Comment by zurkoxxx** [comment]
Is everything working as expected with local files?
When you open a file is the file name _italic_? (if it is _italic_, just double click it)

**Comment by JeremyBackus** [comment]
Apparently this is a feature of VS Code called preview mode.  You can turn it off by adding a line to your user settings.  

,"workbench.editor.enablePreview": false
