### ISSUE TITLE
Vscode remote workspace cannot work fun with cpptools.

### ISSUE THREAD

**Issue by mirsking** [mkloubert/vscode-remote-workspace#33]
When I use remote workspace to map a remote c++ project directory to vscode and open a file with .cpp extension，[cpptools](https://github.com/Microsoft/vscode-cpptools) tried to start for cpp code intellisense but just failed with the following errors:

* Unable to start the C/C++ language server. IntelliSense features will be disabled. Error: Launching server using command ~/.vscode/extensions/ms-vscode.cpptools-0.17.6/bin/Microsoft.VSCode.CPP.Extension.darwin failed.
* Couldn't start client cpptools: 

I'm using vscode on Mac.

**Comment by mkloubert** [comment]
@mirsking 

cpptools itself must be able to work with URIs, handled by new [FileSystemProvider API](https://code.visualstudio.com/docs/extensionAPI/vscode-api#FileSystemProvider).

This seems to similar to [linting and formatting](https://github.com/mkloubert/vscode-remote-workspace/issues/2).
