### ISSUE TITLE
Pageant support for SFTP is missing

### ISSUE THREAD

**Issue by tkoelpin** [mkloubert/vscode-remote-workspace#37]
Hello,

I want to use the remote workspace with an pageant authentication. I don't see any descriptions in the tutorial how I could use them, if the remote workspace already supports pageant.

For this, the password sector should be an optional parameter or better should be prohibted / disallowed.

Many thanks for your support in advance.

**Comment by mkloubert** [comment]
@tkoelpin 

Are you talking about something, like a username / password prompt?

**Comment by tkoelpin** [comment]
Good Morning,

no I am talking about an ssh-agent implementation with a given username. The ssh-agent contains my private Key, so I used this method for a safer authentication.

My question is right now: How could I implement this?

Thank you so much for your support in advance.

Greetings from Bremen, Germany to Stolberg, Germany ;-)

**Comment by mkloubert** [comment]
@tkoelpin 

Ah, OK :-)

You can setup `key` and `phrase` [URL parameters](https://github.com/mkloubert/vscode-remote-workspace#sftp-).

**Comment by tkoelpin** [comment]
Hi again @mkloubert ,

I tried to connect like this

```` 
sftp://username@hostname/path/to/workspace?npPhraseFile=1&key=C:\\path\\to\\key.ppk&phrase=UnlockPhrase
````

But my Question is now:
Should I use URL encoded parameters for file paths and `phrase`?

Thank you so much for your support in advance.

**Comment by mkloubert** [comment]
Yes try this.

**Comment by tkoelpin** [comment]
Oh, it doesn't work. Neither with encodeURI() nor with encodeURIComponent() works here ...

**Comment by schrej** [comment]
If you use `?agent=pageant` it uses Pageant correctly.

**Comment by tkoelpin** [comment]
Hello Marcel,

yes, that was the solution that I was looking for a long time. __Many thanks up to you!__

__Keep it up on your good work!__ :+1:

Best regards
Tobias K.
