### ISSUE TITLE
Feature request: Can you add keep alive to SFTP connections?

### ISSUE THREAD

**Issue by weikai** [mkloubert/vscode-remote-workspace#41]
The CIS harden machines will kick SFTP connections after 5 minutes without activities.  Can you add an option to ping the server every minute to keep SFTP connection alive?

**Comment by mkloubert** [comment]
@weikai 

Have you tried [keepAlive parameter](https://github.com/mkloubert/vscode-remote-workspace#parameters--5)?

**Comment by weikai** [comment]
Thank you @mkloubert.  I missed that parameter.  It's working great!
