### ISSUE TITLE
Can't open .code-workspace file with "File >> Open Workspace..." GUI

### ISSUE THREAD

**Issue by phillynch7** [mkloubert/vscode-remote-workspace#44]
On Mac dotfiles aren't shown by default in the "Open Workspace..." GUI. This can be solved by "cmd-shift-." to show all files, but VSCode doesn't allow me to open the `.code-workspace` file. Is there another way to open it as a workspace?

**Comment by phillynch7** [comment]
I did not realize that the `.code-workspace` was meant to be a file extension, not a dotfile. Maybe I just didn't have enough coffee, but the the "How to use" wasn't clear to me. I only figured out what I was doing wrong by noticing in the gif preview that it was a `test.code-workspace` that was opened. Hopefully this helps anyone else with the same problem I had.

**Comment by freezer-glp** [comment]
thanks, this really helps me!
