### ISSUE TITLE
it is bad idea to have passphrase for key file in raw form

### ISSUE THREAD

**Issue by 07pepa** [mkloubert/vscode-remote-workspace#57]
Hi there.... I think it is bad idea to save passphrase in raw form (except in brain matter)

Please add option to omit passprase and allow to key it in like [this](https://github.com/liximomo/vscode-remote-fs) extension

**Comment by mkloubert** [comment]
@07pepa @lamaorange

It already does: https://github.com/mkloubert/vscode-remote-workspace#parameters--5
