### ISSUE TITLE
You've been featured! 🎉

### ISSUE THREAD

**Issue by auchenberg** [mkloubert/vscode-remote-workspace#58]
Hi there 👋

It's Kenneth from the VS Code team. I'm writing to let you know that your extension have been featured in our marketplace, https://marketplace.visualstudio.com/VSCode, so expect a bump in installs, usage and incoming issues.

Thanks for building this awesome extension for VS Code!

/k

**Comment by mkloubert** [comment]
WHAT AN HONOR :-)

Yes, I will have a lot of work to do the next days, but this is GREAT :-)

Thanks for the support!
