### ISSUE TITLE
Ftp problem

### ISSUE THREAD

**Issue by drpark** [mkloubert/vscode-remote-workspace#59]
Hi,
it works fine with some sftp server (gandi for example),

but i tried with several ftp servers (ovh, 1and1..) and it does'nt really work...the connection is really long, impossible to browse through the tree, and to open files.

if i try in sftp on these same servers, browsing is ok, but impossible to save...

thanks for help.
Regards,

**Comment by mkloubert** [comment]
@drpark 

What do your [logs](https://github.com/mkloubert/vscode-remote-workspace#logs-) say?

Have you tried to activate `debug` parameter on [SFTP](https://github.com/mkloubert/vscode-remote-workspace#sftp-)?

For FTP: Do you use [FTP](https://github.com/mkloubert/vscode-remote-workspace#ftp-) or [FTPs](https://github.com/mkloubert/vscode-remote-workspace#ftps-) scheme?

**Comment by drpark** [comment]
@mkloubert nothing special , some missing files on ftp but it says the same to sftp
I can give you a trial account on the ftp server if it might help...
Regards

**Comment by mkloubert** [comment]
@drpark

great! thats helps a lot to debug!

**Comment by drpark** [comment]
@mkloubert here is a wetransfert link to get one test workspace, thank you
https://wetransfer.com/downloads/446ff222445ed3c627f093652207db8420181006095339/b24bd254f345117c09a58ad3d03d312020181006095339/e3e3da

**Comment by mkloubert** [comment]
@drpark 

Thanks I lot! I could reproduce the issue, fixed it and can connect to the server now.

Seems that the extension opens too many connections to the server, because VSCode starts some default requests at the same time.

At the beginning, VSCode tries to access the following folders and files like:

* `.git/config`
* `.vscode`
* `.vscode/extensions.json`
* `.vscode/settings.json`
* `nodes_modules`

Of course this will create "a lot" of connections that the same time.

I implemented a connection queue, which seems to reduce the number of open connections.

I will test it today and try to release a fix that weekend.

**Comment by drpark** [comment]
Great thank you ! 

 

 

 

De : Marcel Kloubert <notifications@github.com> 
Envoyé : samedi 6 octobre 2018 13:06
À : mkloubert/vscode-remote-workspace <vscode-remote-workspace@noreply.github.com>
Cc : drpark <drpark@free.fr>; Mention <mention@noreply.github.com>
Objet : Re: [mkloubert/vscode-remote-workspace] Ftp problem (#59)

 

@drpark <https://github.com/drpark> 

Thanks I lot! I could reproduce the issue, fixed it and can connect to the server now.

Seems that the extension opens too many connections to the server, because VSCode starts some default requests at the same time.

At the beginning, VSCode tries to access the following folders and files like:

*	.git/config
*	.vscode
*	.vscode/extensions.json
*	.vscode/settings.json
*	nodes_modules

Of course this will create "a lot" of connections that the same time.

I implemented a connection queue, which seems to reduce the number of open connections.

I will test it today and try to release a fix that weekend.

**Comment by mkloubert** [comment]
@drpark 

**I have released a new version 0.34.0**, and fixed the problem by implementing a queue for handling actions inside a connection at once.

If you have problems, you can try to play with the following, new [parameters](https://github.com/mkloubert/vscode-remote-workspace#parameters--2):

* `queue`
* `queueSize`
