### ISSUE TITLE
Allow for SSH_AUTH_SOCK substitution in target -> agent setting

### ISSUE THREAD

**Issue by pareyesv** [mkloubert/vscode-remote-workspace#60]
See https://github.com/mkloubert/vs-deploy/issues/63

Same issue here. The goal is to set `"agent": "${SSH_AUTH_SOCK}"`.

Example:

```
// test.code-workspace
{
    "folders": [
        {
            "uri": "sftp://username@host:path/?params=sftp_uri_params.json",
            "name": "My SFTP folder"
        }
    ],
}
```

```
// sftp_uri_params.json
{
    "agent": "${SSH_AUTH_SOCK}",
    "agentForward": 1
}
```

**Comment by mkloubert** [comment]
@pareyesv 

**[Placeholders](https://github.com/mkloubert/vscode-remote-workspace#placeholders-) are available since version 0.33.0 now.**
