### ISSUE TITLE
cant connect SFTP with password including '#'

### ISSUE THREAD

**Issue by hiratamasato** [mkloubert/vscode-remote-workspace#65]
problem: 
i don't use public key authentication, so try to connect the server with sftp with password like this
"sftp://my-user:my-password@sftp.example.com/"
but return error response '(Error) Invalid username'

try:
password including '#' can return above error response.
password not including '#'(like 'aaaa') return with reasonable message like below
'(Error) All configured authentication methods failed'

is this a bug of vscode-remote-workspace?

**Comment by mkloubert** [comment]
@hiratamasato 

No, this is how VSCode (and other software) handles URIs.

You have to encode special chars like `#` with things like, in that case, `%23`:

For example: `Password#xyz` has to be saved as `Password%23xyz`.

**Comment by hiratamasato** [comment]
thank you for your answer!
i certenly understand URI encode is needed.

**Comment by sayajin101** [comment]
I also had a password with a hash in and the above solution worked 100% ty
