### ISSUE TITLE
Cant save files after update

### ISSUE THREAD

**Issue by peon501** [mkloubert/vscode-remote-workspace#66]
Cant save files via sftp after update

**Comment by mkloubert** [comment]
@peon501 

**Should be fixed since version 0.35.1.**

If this does not work, try to set `queue` URI parameter to `0`

**Comment by peon501** [comment]
throw me JSON example please :)

**Comment by peon501** [comment]
Nevermind ok ty :)

**Comment by peon501** [comment]
it works, ty for fix :)
