### ISSUE TITLE
password with %

### ISSUE THREAD

**Issue by ceceghini** [mkloubert/vscode-remote-workspace#79]
I have a password with % character
By parameter url I replaced% with %25, but the connection happens while browsing I can not see files and folders

**Comment by mkloubert** [comment]
@ceceghini 

SFTP?

**Comment by ceceghini** [comment]
yes

**Comment by mkloubert** [comment]
@ceceghini 

I could reproduce the issue and it seems to be an issue in the URI parsing / handling in VSCode.

Workarround: Create a text file (like `sftp_auth.txt`) and write your username and password there:

```
myUser:myPass%word
```

and use an URI like that:

```
sftp://localhost/?auth=sftp_auth.txt
```

I think the problem that VSCode has currently a bug to create new URIs from a staring URI if special chars like `%` are in it.

**Comment by henrique-voni** [comment]
Hey i'm having the same problem because my pass has `@`. But it is not working with the txt file.
