### ISSUE TITLE
prevent logging

### ISSUE THREAD

**Issue by drpark** [mkloubert/vscode-remote-workspace#83]
Hi,
it would be great that logging is disabled by default and allowing logging only if log:1 in config files.
For security reason (notebook stealing for example)

thank you

**Comment by mkloubert** [comment]
@drpark 

can you give me an example url and/or config?

**Comment by drpark** [comment]
@mkloubert 

{
  "folders": [{
      "uri": "sftp://mylogin:mypassword@sftp.sd3.gpaas.net/lamp0/web/",
      "name": "DY1",
	  "debug":0
  }]
}

i get this in logs

TRACE fs.sftp.sftpfilesystem.forconnection() - [13/Jan/2019:08:52:06 +0000] "(EntryNotFound (FileSystemError)) sftp://mylogin:mypassword@sftp.sd3.gpaas.net/lamp0/web//.git/config

which contains my login and password on the last line
so the better things would be to totally disable logging in options something like this for security purpose

{
  "folders": [{
      "uri": "sftp://mylogin:mypassword@sftp.sd3.gpaas.net/lamp0/web/",
      "name": "DY1",
	  "debug":0,
"log":0
  }]
}

**Comment by mkloubert** [comment]
@drpark 

**Since version 0.40.0**, credentials should be removed / invisible.

**Comment by drpark** [comment]
@mkloubert great! thank you.
